version: "3"
services:
  terraform:
          image: nonbin/aws-ter-ansible
          build: .
          volumes: 
            - terraform-data:/terraform

volumes:
  terraform-data:
     driver: local


